# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 1046)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1141, 971))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.NextBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.NextBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.NextBtn.setObjectName("NextBtn")
        self.gridLayout.addWidget(self.NextBtn, 5, 4, 1, 1)
        self.ImageFolderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ImageFolderBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ImageFolderBtn.setObjectName("ImageFolderBtn")
        self.gridLayout.addWidget(self.ImageFolderBtn, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 4, 1, 1, 7)
        self.RightFolderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RightFolderBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.RightFolderBtn.setObjectName("RightFolderBtn")
        self.gridLayout.addWidget(self.RightFolderBtn, 1, 0, 1, 1)
        self.DeleteFolerText = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DeleteFolerText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DeleteFolerText.setObjectName("DeleteFolerText")
        self.gridLayout.addWidget(self.DeleteFolerText, 2, 1, 1, 7)
        self.DeleteFolerBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DeleteFolerBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.DeleteFolerBtn.setObjectName("DeleteFolerBtn")
        self.gridLayout.addWidget(self.DeleteFolerBtn, 2, 0, 1, 1)
        self.imageinfoText = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.imageinfoText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.imageinfoText.setObjectName("imageinfoText")
        self.gridLayout.addWidget(self.imageinfoText, 3, 1, 1, 7)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(150, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.KeepBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.KeepBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.KeepBtn.setObjectName("KeepBtn")
        self.gridLayout.addWidget(self.KeepBtn, 5, 6, 1, 1)
        self.RightFolerText = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.RightFolerText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.RightFolerText.setObjectName("RightFolerText")
        self.gridLayout.addWidget(self.RightFolerText, 1, 1, 1, 7)
        self.DeleteBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DeleteBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.gridLayout.addWidget(self.DeleteBtn, 5, 1, 1, 1)
        self.ImageFolerText = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ImageFolerText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ImageFolerText.setObjectName("ImageFolerText")
        self.gridLayout.addWidget(self.ImageFolerText, 0, 1, 1, 7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NextBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>跳过，不做处理</p></body></html>"))
        self.NextBtn.setText(_translate("MainWindow", "Next(N)"))
        self.ImageFolderBtn.setText(_translate("MainWindow", "Image Foler"))
        self.RightFolderBtn.setText(_translate("MainWindow", "Right Foler"))
        self.DeleteFolerBtn.setText(_translate("MainWindow", "Delete Foler"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "    image name"))
        self.KeepBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>移动到 Right Folder 文件夹</p></body></html>"))
        self.KeepBtn.setText(_translate("MainWindow", "Keep(K)"))
        self.KeepBtn.setShortcut(_translate("MainWindow", "K"))
        self.DeleteBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>移动到 Delete Folder 文件夹</p></body></html>"))
        self.DeleteBtn.setText(_translate("MainWindow", "Delete(D)"))
        self.DeleteBtn.setShortcut(_translate("MainWindow", "D"))

